### ISSUE TITLE
why-run mode not working when using this cookbook

### ISSUE THREAD

**Issue by bleything** [rackspace-cookbooks/chef-slack_handler#31]
I noticed that why-run mode is broken when this cookbook is in my runlist. I'm guessing that this is due to handlers not being loaded in why-run (see chef-cookbooks/chef_handler#40):

```
  * chef_handler[Chef::Handler::Slack] action enable
    - Would disable Chef::Handler::Slack as a start handler
    - Would disable Chef::Handler::Slack as a report handler
    - Would disable Chef::Handler::Slack as a exception handler
    - Would load Chef::Handler::Slack from /var/chef/handlers/slack_handler_webhook.rb
    ================================================================================
    Error executing action `enable` on resource 'chef_handler[Chef::Handler::Slack]'
    ================================================================================

    NameError
    ---------
    uninitialized constant Slack

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/chef_handler/libraries/helpers.rb:51:in `const_get'
    /var/chef/cache/cookbooks/chef_handler/libraries/helpers.rb:51:in `get_class'
    /var/chef/cache/cookbooks/chef_handler/providers/default.rb:48:in `block in class_from_file'
    /var/chef/cache/cookbooks/slack_handler/recipes/default.rb:58:in `from_file'
    /var/chef/cache/cookbooks/orcasnet/recipes/default.rb:20:in `from_file'
```

Honestly, I'm not sure whether there's anything about the Slack handler recipe that could change to fix this. I'm not sure why it's even looking up the constant in the first place. But... maybe you have some ideas?

**Comment by bleything** [comment]
Further investigation showed that this is due to the changes in chef_handler 1.4.0, so I'ma close this. Sorry for the noise!
