### ISSUE TITLE
NameError: uninitialized constant Chef::Handler::Slack

### ISSUE THREAD

**Issue by ezequiels** [rackspace-cookbooks/chef-slack_handler#48]
I'm executing:
chef-client -o 'recipe[existing], 'recipe[newrecipe]' --why-run 
on a server to test the second recipe without having to add it to the run-list. 
My existing recipe contains the handler and a bunch of other recipes.
When adding the recipe to the run-list, there is no issue. 
When running the command above, an error presents itself:

Cookbook Trace:
  ---------------
    /var/chef/cache/cookbooks/chef_handler/libraries/helpers.rb:51:in `get_class'
    /var/chef/cache/cookbooks/chef_handler/providers/default.rb:48:in `block in class_from_file'
    /var/chef/cache/cookbooks/cpla_b_handler_mattermost/recipes/default.rb:58:in `from_file'
    /var/chef/cache/cookbooks/cpla_r_core/recipes/default.rb:10:in `from_file'

  Relevant File Content:
  ----------------------
  /var/chef/cache/cookbooks/chef_handler/libraries/helpers.rb:

   44:        ancestors = class_full_name.split('::')
   45:        class_name = ancestors.pop
   46:
   47:        # We need to search the ancestors only for the first/uppermost namespace of the class, so we
   48:        # need to enable the #const_get inherit paramenter only when we are searching in Kernel scope
   49:        # (see COOK-4117).
   50:        parent = ancestors.inject(Kernel) { |scope, const_name| scope.const_get(const_name, scope === Kernel) }
   51>>       child = parent.const_get(class_name, parent === Kernel)
   52:        [parent, child]
   53:      end
   54:    end
   55:  end
   56:

**Comment by TheSeubert** [comment]
Looking at your stack trace there, it seems the error is being reported from the chef_handler cookbook and not ours specifically. The problem is that slack_handler does not support why_run which is bubbling up from chef_handler supporting it. You can read more on this in the closed issue here:

https://github.com/chef-cookbooks/chef_handler/issues/41

I don't see this functionally impairing the cookbook directly except why_run mode and might not be implemented soon at all unless someone else is willing to take a look and PR this.
